### ISSUE TITLE
SB 7.0 Compatibility

### ISSUE THREAD

**Issue by drush** [stevensacks/storybook-mobile-addon#1]
Adding a tracking issue for compatibility with the upcoming version of SB.

**Comment by stevensacks** [comment]
@jonniebigodes Thanks for reaching out. I will check the migration guide and make the required changes.

**Comment by jonniebigodes** [comment]
@stevensacks, no need to thank whatsoever. It was my pleasure. Looking forward to seeing the addon updated 🙏

**Comment by stevensacks** [comment]
@jonniebigodes I am having issues updating to Storybook 7. There's some kind of internal error with `@storybook/theming` when it tries to render the panel.

Could you please take a look and see if you can figure it out?

https://github.com/stevensacks/storybook-mobile-addon/pull/2

```typescript
caught TypeError: Cannot read properties of undefined (reading 'size')
    at G (utils.ts:476:56)
    at ge (index.mjs:3:2769)
    at ae (index.mjs:6:2111)
    at index.mjs:12:7500
    at index.mjs:6:2806
    at renderWithHooks (chunk-FGVEHHDQ.mjs:69:936)
    at updateForwardRef (chunk-FGVEHHDQ.mjs:69:43485)
    at beginWork (chunk-FGVEHHDQ.mjs:71:22415)
    at HTMLUnknownElement.callCallback2 (chunk-FGVEHHDQ.mjs:2:1922)
    at Object.invokeGuardedCallbackDev (chunk-FGVEHHDQ.mjs:2:2446)
```

**Comment by stevensacks** [comment]
Solved it. SB 7 support is complete.

**Comment by jonniebigodes** [comment]
@stevensacks, sorry for the delayed response and not being able to follow up with you, but I was wrapping up the 7.0 release. It's great to hear that you solved the issue and the addon supports Storybook 7.0. I'm going to update the issue where we're tracking the state of addons. 


Hope you have a great weekend.

Stay safe
